Improvement in UI of Footer section
Susmita-Dey/Sukoon pull request #228
Opened 2022-08-14 12:56 UTC by ShivanshAr97

The interface of footer sector has been improved

**Screenshot**
![image](https://user-images.githubusercontent.com/96040322/184537928-63e4bb10-da70-4a9c-bdeb-311988a4005e.png)

2022-08-16 01:07 UTC, myhacktech approved these changes

2022-08-19 05:43 UTC, Susmita-Dey requested changes
@ShivanshAr97 You have to make the following changes:
- Fix the merge conflicts in your branch
- Text is not properly aligned in the center with respect to logo
![image](https://user-images.githubusercontent.com/79099734/185551038-6d306dfc-8063-46b3-b1f4-83156ff1ca2b.png)

Also, the logo in the footer itself contains the line you wanna add. Need to think about this. Ping me in discord.


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-19 08:21 UTC, merged

2022-08-19 12:05 UTC, myhacktech commented
@ShivanshAr97 mention issue no?

2022-08-19 12:12 UTC, ShivanshAr97 commented
@myhacktech issue no. #222