Issue name : Improving the navigation bar UI
Susmita-Dey/Sukoon pull request #330
Opened 2022-08-26 15:13 UTC by Kritika0035

Fixed the navigation bar of the UI, issue no. 289.
SSOC member.
![Screenshot (198)](https://user-images.githubusercontent.com/92821377/186937025-bdd3bdfc-6130-4bd8-822a-9f753adf4b6f.png)

2022-08-26 16:32 UTC, myhacktech commented
![Uploading Screenshot (706).png…]()
try to improve this

2022-08-26 16:46 UTC, Kritika0035 commented
The picture isn't visible

2022-08-27 06:36 UTC, myhacktech commented
> The picture isn't visible

![Screenshot (706)](https://user-images.githubusercontent.com/86517958/187018276-e472b23a-e085-4d00-a369-a4cb4ef3816b.png)

2022-08-27 06:41 UTC, Kritika0035 commented
okay I will fix it

2022-09-09 05:53 UTC, Susmita-Dey reviewed
Any updates?

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

2022-09-09 05:54 UTC, Susmita-Dey requested changes
@Kritika0035 Your branch has merge conflicts. Kindly fix it.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-09-09 09:45 UTC, AliReza1083 reviewed
I reviewed your codes, and I came up with this.
Wish you all the best.

2022-09-09 09:45 UTC, AliReza1083 commented on css/style.css
> +  transition: 0.5s ease-in-out;
If you want to code like a professional, there is no need to code like this:
```diff
- transition: 0.3s ease-in-out;
+ transition: .3s ease-in-out;
```
Overall looking Great.

2022-09-22 07:01 UTC, closed without merging