Made Footer Revealable
Susmita-Dey/Sukoon pull request #351
Opened 2022-08-29 08:51 UTC by MridulTi

I made the Footer Revealable for all pages except Talking Therapy. I also added a div in Loading Id as it goes affected due to position: sticky I used in the Footer class.
Earlier Footer:-
![image](https://user-images.githubusercontent.com/92802892/187162527-a94e1238-ea31-44b6-935f-72ee77779e7b.png)

Updated revealable Footer:-
![image](https://user-images.githubusercontent.com/92802892/187162853-389f838b-ec5c-4384-bbc2-5a4c8368f67d.png)
![image](https://user-images.githubusercontent.com/92802892/187162898-f4b67302-a2ce-4baa-bebc-3c6a0b94f230.png)

2022-08-30 10:03 UTC, myhacktech approved these changes

2022-09-08 22:16 UTC, AliReza1083 reviewed
If You follow this step, Your code will look nicer.
Wish you all the best.

2022-09-08 22:16 UTC, AliReza1083 commented on html/yogatherapy.html
> +        <img src="https://preview.colorlib.com/theme/yogabest/images/xabout.png.pagespeed.ic.H7uxRdWOgu.webp" width="700"
The code seems to be amazing but it's better to write the **width** and **height** of an image in CSS file.

``` diff
- <img src="" width="700" height="600">
+ img { width: 700px; height: 600px;}
```

> **Note**
> Why should we use it in CSS file?
1. For making the code to looks clear for code reader.
2. For making Responsive

2022-09-08 22:16 UTC, AliReza1083 commented on html/yogatherapy.html
> +            <a href="https://www.artofliving.org/in-en/yoga/yoga-poses/warrior-pose-virbhadrasana"><button>Read
If you are using a tag, There is no need use **_button_** inside of it.
You can design it to look like a button.

``` diff
- <a href=""><button></button></a>
+ <a href=""></a>
```

> **Note**
> For styling a tag, If you want to add `padding` on it, set the display to equal to `inline-block`.

>**Warning**
> If you don't use `inline-block`, The `padding-top` and `padding-bottom` is not going to work.

2022-09-09 06:02 UTC, Susmita-Dey requested changes
@MridulTi Your PR would break the whole website. Kindly check the deploy link. It's horrible. Also, your PR has merge conflicts.

I don't think we should approve this PR and merge it.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Brittle, Not maintainable

2022-09-09 11:14 UTC, MridulTi commented
> t maintainable

I don't understand as to why there is merge conflict even after I resolved it once

2022-09-22 07:12 UTC, closed without merging