Fix Issue: #310 Changing the design of the Navbar on Yoga therapy page and also fixing its position
Susmita-Dey/Sukoon pull request #362
Opened 2022-09-03 16:22 UTC by SahilDahekar

- Issue no #310 
- Added new color theme to menu.
- Added new animation and position to the menu.
- Added svg toggling function (Toggles between hamburger and "X" ).
- Fixed the position of the menu so that it does not scroll with the content.
- Added hover to hamburger and menu links and with closing function on redirecting to a part of the page.
- Decreased the unneccessary large height of the navbar.

<img width="944" alt="Screenshot 2022-09-03 214308" src="https://user-images.githubusercontent.com/97726887/188279448-ec18a143-9b7b-41fb-a429-d072c7b9b09e.png">
<img width="361" alt="Screenshot 2022-09-03 214328" src="https://user-images.githubusercontent.com/97726887/188279453-5ab36ea5-addb-4071-8f41-5a955b52ec9b.png">
<img width="361" alt="Screenshot 2022-09-03 214347" src="https://user-images.githubusercontent.com/97726887/188279456-d21c58b2-ee09-47ca-8619-534b4d77b263.png">

2022-09-08 08:49 UTC, myhacktech approved these changes

2022-09-09 06:14 UTC, Susmita-Dey requested changes
@SahilDahekar Fix the merge conflicts

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

2022-09-10 08:35 UTC, SahilDahekar commented
@Susmita-Dey Merge conflicts are resolved

2022-09-10 13:08 UTC, Susmita-Dey approved these changes
LGTM.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-09-10 13:09 UTC, merged