Changed Article and Summary section info to a hoverable
Susmita-Dey/Sukoon pull request #374
Opened 2022-09-10 08:12 UTC by MridulTi

### Describe the PR
Solved the Issue #363
I asked to change the article and summary of books section from embedded webpages to a still image which on hover shows some information about the image with the link to the original page to look into.

### Original Screenshot
![image](https://user-images.githubusercontent.com/92802892/189474991-31793c47-590b-45b7-90b2-cb51d81ffed3.png)

### Updated Screenshot
![image](https://user-images.githubusercontent.com/92802892/189475001-7ce66309-7ffa-4d5e-ad04-9fb0deddd581.png)
On HOVER:-
![image](https://user-images.githubusercontent.com/92802892/189475017-72cfd2ec-49b8-4dd8-939b-aa3f5ba8b48f.png)

2022-09-10 08:20 UTC, imaaquibali approved these changes

2022-09-10 08:25 UTC, imaaquibali commented
@MridulTi Brother on hovring the section just show the title of the section remove the summery and also  add **Read More** **button** on every section.  It's look good.

2022-09-10 08:29 UTC, MridulTi commented
> **ead More** **b**

So, let me make sure if this is what you mean, you mean to remove the summary on hover, and also do you want the Read More button on every hover or on Every Section, cause there is no link available that I can attach to Readmore for every section there?

2022-09-10 12:51 UTC, Susmita-Dey commented
@MridulTi Why there's a horizontal scrolling here?
![image](https://user-images.githubusercontent.com/79099734/189484166-206bb5db-0d3e-4218-9200-275d00d292e9.png)


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-09-10 13:21 UTC, MridulTi commented
> @MridulTi Why there's a horizontal scrolling here? ![image](https://user-images.githubusercontent.com/79099734/189484166-206bb5db-0d3e-4218-9200-275d00d292e9.png)
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Its for smaller screens so that the screen doesn't look too clogged up which was the reason this issue was raised my me .

2022-09-10 13:42 UTC, Susmita-Dey commented
@MridulTi Instead of scrolling, you can shift some items down by using grid

2022-09-10 13:45 UTC, MridulTi commented
> @MridulTi Instead of scrolling, you can shift some items down by using grid

Ok, then I will Apply it right now.

2022-09-10 14:11 UTC, MridulTi commented
> @MridulTi Instead of scrolling, you can shift some items down by using grid
Does this look right?
![image](https://user-images.githubusercontent.com/92802892/189487186-a8521de9-8f7e-46a3-98f1-0f3c2e9df5d7.png)
I changed it so please view it through preview

2022-09-11 14:32 UTC, Susmita-Dey commented
@MridulTi Your changes are not reflected in the deploy preview. What shall I do?

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Not reusable

2022-09-12 00:50 UTC, MridulTi commented
> @MridulTi Your changes are not reflected in the deploy preview. What shall I do?
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question  |  **Tags:** Not reusable

What? But I can clearly see my changes in the deploy preview
Here is the video link I recorded just now showing that
https://drive.google.com/file/d/1CDnRTsraunaT9_6SSs65qzh-c0iOZ_W9/view?usp=sharing

2022-09-12 03:22 UTC, Susmita-Dey commented
@MridulTi I got it. Your screen size is bigger taht's why it's visible to you.

2022-09-12 03:29 UTC, Susmita-Dey requested changes
Pull the recent changes once again and make the section responsive for all screen size as the articles is disappearing at a certain screen size.
![image](https://user-images.githubusercontent.com/79099734/189568705-104aab72-5e38-401d-8a4c-55d4e3862916.png)

Kindly fix it.

2022-09-12 15:06 UTC, MridulTi commented
> Pull the recent changes once again and make the section responsive for all screen size as the articles is disappearing at a certain screen size. ![image](https://user-images.githubusercontent.com/79099734/189568705-104aab72-5e38-401d-8a4c-55d4e3862916.png)
> 
> Kindly fix it.

I fixed it kindly check it.

2022-09-13 06:51 UTC, Susmita-Dey commented
@MridulTi Can you share a video for that as your changes are not reflected in the deploy preview?

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Not reusable

2022-09-13 13:17 UTC, MridulTi commented
> @MridulTi Can you share a video for that as your changes are not reflected in the deploy preview?
> 
> __ [![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966)](https://semasoftware.com/gh) [ ![sema-logo](https://camo.githubusercontent.com/843687ee2a84b8cc104a1e4297c26c9db3d3f710080228887db6338b4550a240/68747470733a2f2f6170702e73656d61736f6674776172652e636f6d2f696d672f73656d612d747261792d6c6f676f2e676966) ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** ❓ I have a question  |  **Tags:** Not reusable

Sure , Here is the link https://drive.google.com/file/d/154FSUa_aYystTZcbKhTrRl9_RcpqIE0M/view?usp=sharing

2023-01-02 23:27 UTC, AliReza1083 approved these changes
Nice Work...
The result of My Code Review 👇

2023-01-02 23:27 UTC, AliReza1083 commented on html/readingTherapy.html
> +              <button class="butn-red"><a href="https://www.developgoodhabits.com/inspirational-stories/" target="_blank">Read More</a></button>
Can we change the class name `butn-red` to `btn-red`?

Most of the developer use btn, and easy to read.

2023-01-02 23:27 UTC, AliReza1083 commented on css/readingTherapy.css
> +.collage-card>div>img{
It'd be great, If we add space between them.

2023-01-03 05:06 UTC, Susmita-Dey commented
Merge conflicts

2023-07-04 04:11 UTC, closed without merging